master_mapping:
  master_config.yaml:
    resource: master_config
    driver: fuel_external_git.drivers.yaml_driver.YamlConfig
    path: ''
resource_mapping:
  ceilometer-api-paste.ini:
    path: /etc/ceilometer/api-paste.ini
    resource: ceilometer_api_paste_ini
  ceilometer.conf:
    path: /etc/ceilometer/ceilometer.conf
    resource: ceilometer
  cinder-api-paste.ini:
    path: /etc/cinder/api-paste.ini
    resource: cinder_api_paste_ini
  cinder.conf:
    path: /etc/cinder/cinder.conf
    resource: cinder
  dhcp_agent.ini:
    path: /etc/neutron/dhcp_agent.ini
    resource: neutron_dhcp_agent_config
  glance-api.conf:
    path: /etc/glance/glance-api.conf
    resource: glance_api
  glance-cache.conf:
    path: /etc/glance/glance-cache.conf
    resource: glance_cache
  glance-glare.conf:
    path: /etc/glance/glance-glare.conf
    resource: glare_config
  glance-registry.conf:
    path: /etc/glance/glance-registry.conf
    resource: glance_registry
  heat-api-paste.ini:
    path: /etc/heat/api-paste.ini
    resource: heat_api_paste_ini
  heat.conf:
    path: /etc/heat/heat.conf
    resource: heat
  keystone.conf:
    path: /etc/keystone/keystone.conf
    resource: keystone_config
  l3_agent.ini:
    path: /etc/neutron/l3_agent.ini
    resource: neutron_l3_agent_config
  metadata_agent.ini:
    path: /etc/neutron/metadata_agent.ini
    resource: neutron_metadata_agent_config
  ml2_conf.ini:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    resource: neutron_plugin_ml2
  neutron-api-paste.ini:
    path: /etc/neutron/api-paste.ini
    resource: neutron_api_config
  neutron.conf:
    path: /etc/neutron/neutron.conf
    resource: neutron_config
  nova-api-paste.ini:
    path: /etc/nova/api-paste.ini
    resource: nova_paste_api_ini
  nova.conf:
    path: /etc/nova/nova.conf
    resource: nova_config
  openvswitch_agent.ini:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    resource: neutron_agent_ovs
  sriov_agent.ini:
    path: /etc/neutron/plugins/ml2/sriov_agent.ini
    resource: neutron_sriov_agent_config
