resource_mapping:
  ceilometer_api_paste_ini:
    alias: ceilometer-api-paste.ini
    path: /etc/ceilometer/api-paste.ini
  ceilometer:
    alias: ceilometer.conf
    path: /etc/ceilometer/ceilometer.conf
  cinder_api_paste_ini:
    alias: cinder-api-paste.ini
    path: /etc/cinder/api-paste.ini
  cinder:
    alias: cinder.conf
    path: /etc/cinder/cinder.conf
  glance_api:
    alias: glance-api.conf
    path: /etc/glance/glance-api.conf
  glance_cache:
    alias: glance-cache.conf
    path: /etc/glance/glance-cache.conf
  glare_config:
    alias: glance-glare.conf
    path: /etc/glance/glance-glare.conf
  glance_registry:
    alias: glance-registry.conf
    path: /etc/glance/glance-registry.conf
  heat_api_paste_ini:
    alias: heat-api-paste.ini
    path: /etc/heat/api-paste.ini
  heat:
    alias: heat.conf
    path: /etc/heat/heat.conf
  keystone_config:
    alias: keystone.conf
    path: /etc/keystone/keystone.conf
  neutron_agent_ovs:
    alias: openvswitch_agent.ini
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
  neutron_api_config:
    alias: neutron-api-paste.ini
    path: /etc/neutron/api-paste.ini
  neutron_config:
    alias: neutron.conf
    path: /etc/neutron/neutron.conf
  neutron_dhcp_agent_config:
    alias: dhcp_agent.ini
    path: /etc/neutron/dhcp_agent.ini
  neutron_l3_agent_config:
    alias: l3_agent.ini
    path: /etc/neutron/l3_agent.ini
  neutron_metadata_agent_config:
    alias: metadata_agent.ini
    path: /etc/neutron/metadata_agent.ini
  neutron_plugin_ml2:
    alias: ml2_conf.ini
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
  neutron_sriov_agent_config:
    alias: sriov_agent.ini
    path: /etc/neutron/plugins/ml2/sriov_agent.ini
  nova_config:
    alias: nova.conf
    path: /etc/nova/nova.conf
  nova_paste_api_ini:
    alias: nova-api-paste.ini
    path: /etc/nova/api-paste.ini
  master_config:
    alias: master_config.yaml
    path: ""
    driver: 'fuel_external_git.drivers.yaml_driver.YamlConfig'
